# Generated by Django 6.0.6 on 2026-06-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_booking_end_date_alter_booking_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
