# Generated by Django 6.0.6 on 2026-06-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Ghaziabad', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Manual', max_length=20),
        ),
    ]
