# Generated by Django 6.0.6 on 2026-06-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
