# Generated by Django 6.0.6 on 2026-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_booking_coupon_booking_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='billing_status',
            field=models.CharField(choices=[('Settled', 'Settled'), ('Refund Pending', 'Refund Pending'), ('Extra Payment Pending', 'Extra Payment Pending'), ('Refunded', 'Refunded')], default='Settled', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
