# Generated by Django 6.0.6 on 2026-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_booking_billing_status_booking_estimated_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Upcoming', 'Upcoming'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending Payment', max_length=20),
        ),
    ]
